# Generated by Django 4.2.15 on 2024-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metadata',
            field=models.ManyToManyField(blank=True, default=None, help_text='The metadata of the category.', null=True, related_name='categories', to='metadata.metadata'),
        ),
    ]
