# Generated by Django 4.2.15 on 2024-08-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_code_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categorypermission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='categorypermission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='categorypermission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='categorypermission',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='categorypermission',
            name='uuid',
        ),
        migrations.AddIndex(
            model_name='categorypermission',
            index=models.Index(fields=['code'], name='category_permission_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='categorypermission',
            constraint=models.UniqueConstraint(fields=('code', 'category'), name='unique_category_permission_code'),
        ),
    ]
