# Generated by Django 4.2.15 on 2024-08-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', help_text='The name of the metadata field.', max_length=500)),
                ('placeholder', models.CharField(blank=True, default='', help_text='The placeholder for the metadata field.', max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone'), ('image', 'Image'), ('file', 'File'), ('html', 'HTML'), ('markdown', 'Markdown'), ('color', 'Color'), ('color_hex', 'Color (Hex)'), ('password', 'Password'), ('secret', 'Secret'), ('percentage', 'Percentage'), ('rating', 'Rating'), ('country', 'Country'), ('language', 'Language'), ('timezone', 'Timezone'), ('currency_code', 'Currency Code')], default='text', help_text='The type of the metadata field.', max_length=500)),
                ('is_required', models.BooleanField(default=False, help_text='Whether the metadata field is required or not.')),
                ('is_unique', models.BooleanField(default=False, help_text='Whether the metadata field value is unique accross the folder or not.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('metadata', models.ForeignKey(help_text='The metadata the field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='metadata.metadata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value_text', models.TextField(blank=True, help_text='The text value of the metadata field.', null=True)),
                ('value_integer', models.IntegerField(blank=True, help_text='The integer value of the metadata field.', null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='The decimal value of the metadata field.', max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, help_text='The boolean value of the metadata field.', null=True)),
                ('value_date', models.DateField(blank=True, help_text='The date value of the metadata field.', null=True)),
                ('value_datetime', models.DateTimeField(blank=True, help_text='The datetime value of the metadata field.', null=True)),
                ('value_time', models.TimeField(blank=True, help_text='The time value of the metadata field.', null=True)),
                ('value_url', models.URLField(blank=True, help_text='The URL value of the metadata field.', null=True)),
                ('value_email', models.EmailField(blank=True, help_text='The email value of the metadata field.', max_length=254, null=True)),
                ('value_phone', models.CharField(blank=True, help_text='The phone value of the metadata field.', max_length=20, null=True)),
                ('value_image', models.ImageField(blank=True, help_text='The image value of the metadata field.', null=True, upload_to='images/')),
                ('value_file', models.FileField(blank=True, help_text='The file value of the metadata field.', null=True, upload_to='files/')),
                ('value_html', models.TextField(blank=True, help_text='The HTML value of the metadata field.', null=True)),
                ('value_markdown', models.TextField(blank=True, help_text='The Markdown value of the metadata field.', null=True)),
                ('value_color', models.CharField(blank=True, help_text='The color value of the metadata field.', max_length=20, null=True)),
                ('value_color_hex', models.CharField(blank=True, help_text='The hex color value of the metadata field.', max_length=7, null=True)),
                ('value_password', models.CharField(blank=True, help_text='The password value of the metadata field.', max_length=128, null=True)),
                ('value_secret', models.CharField(blank=True, help_text='The secret value of the metadata field.', max_length=128, null=True)),
                ('value_percentage', models.FloatField(blank=True, help_text='The percentage value of the metadata field.', null=True)),
                ('value_rating', models.IntegerField(blank=True, help_text='The rating value of the metadata field.', null=True)),
                ('value_country', models.CharField(blank=True, help_text='The country value of the metadata field.', max_length=50, null=True)),
                ('value_language', models.CharField(blank=True, help_text='The language value of the metadata field.', max_length=50, null=True)),
                ('value_timezone', models.CharField(blank=True, help_text='The timezone value of the metadata field.', max_length=50, null=True)),
                ('value_currency_code', models.CharField(blank=True, help_text='The currency code value of the metadata field.', max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The document that the metadata value belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='document.document')),
                ('field', models.ForeignKey(help_text='The metadata field that the value belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='metadata.metadatafield')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='metadatafield',
            constraint=models.UniqueConstraint(fields=('name', 'field_type'), name='unique_metadata_name_field_type'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_metadata_name'),
        ),
    ]
