# Generated by Django 4.2.15 on 2024-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metadatafield',
            name='unique_metadata_name_field_type',
        ),
        migrations.AddField(
            model_name='metadatafield',
            name='code',
            field=models.CharField(default=1, help_text='The code of the metadata field.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatafield',
            name='order',
            field=models.IntegerField(default=9999, help_text='The order of the metadata field. Lower the order, higher the priority.'),
        ),
        migrations.AddConstraint(
            model_name='metadatafield',
            constraint=models.UniqueConstraint(fields=('code', 'field_type'), name='unique_metadata_code_field_type'),
        ),
    ]
