# Generated by Django 4.2.15 on 2024-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_remove_metadatafield_unique_metadata_code_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metadatafield',
            name='unique_metadata_name_field_type',
        ),
        migrations.AddConstraint(
            model_name='metadatafield',
            constraint=models.UniqueConstraint(fields=('metadata', 'name', 'field_type'), name='unique_metadata_name_field_type'),
        ),
    ]
