# Generated by Django 4.2.15 on 2024-08-10 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('extension', models.CharField(max_length=256)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
