# Generated by Django 4.2.15 on 2024-08-22 09:00

import apps.document.models.document
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_categorygrouppermission_and_more'),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='category.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=apps.document.models.document.file_location),
        ),
    ]
