name: Deploy to DigitalOcean

name: Deploy to DigitalOcean
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /root/docman
            git pull https://${{ secrets.G_USERNAME }}:${{ secrets.G_TOKEN }}@github.com/Ashikunnabi/docman.git
            docker-compose up -d --build
