name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # Ensure this matches your actual branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DO_SERVER_IP }}  # Store your DigitalOcean IP in GitHub Secrets
          username: ${{ secrets.DO_USERNAME }}  # Store your SSH username in GitHub Secrets (e.g., ubuntu)
          password: ${{ secrets.DO_PASSWORD }}  # Store your SSH password in GitHub Secrets
          script: |
            cd /root/docman
            docker-compose down
            git pull https://${{ secrets.G_USERNAME }}:${{ secrets.G_TOKEN }}@github.com/Ashikunnabi/docman.git
            docker-compose up -d --build
